services:
    mongo:
        image: mongo:7.0.9-jammy
        env_file:
            - .env


    mongo-express:
        image: mongo-express:1.0.2-20-alpine3.19
        ports:
            - 8081:8081
        env_file:
            - .env
    
    backend:
        build: ./backend
        command: bash runserver.sh
        volumes:
            - ./backend:/backend
        ports:
            - 3000:3000
        env_file:
            - .env

