services:
    mongo:
        container_name: ${PROJECT_NAME}-mongo
        image: mongo:7.0.9-jammy
        env_file:
            - .env


    mongo-express:
        container_name: ${PROJECT_NAME}-mongo-express
        image: mongo-express:1.0.2-20-alpine3.19
        ports:
            - 8081:8081
        env_file:
            - .env
    
    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        command: bash runserver.sh
        volumes:
            - ./backend:/backend
        ports:
            - 3000:3000
        env_file:
            - .env
    
    frontend:
        container_name: ${PROJECT_NAME}-frontend
        image: nginx:1.25.2-alpine
        ports:
            - 8080:8080
        volumes:
            - ./frontend/config/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./frontend:/var/www/:ro
        env_file:
            - .env
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
